### ISSUE TITLE
Updating an existing app registration is failing with "Another object with the same value for property uniqueName already exists"

### ISSUE THREAD

**Issue by dougclutter** [microsoftgraph/msgraph-bicep-types#202]
**Bicep version**
Using Azure CLI: Bicep CLI version 0.31.92 (b06509316a)

**Resource and API version**
extension 'br:mcr.microsoft.com/bicep/extensions/microsoftgraph/v1.0:0.1.8-preview'

**Auth flow**
Executed via Bicep CLI using the following command:
az deployment group create --resource-group az-rg-kecka1-01 --template-file deploy.bicep

**Deployment details**
The CLI returned the following error message:
{"status":"Failed","error":{"code":"DeploymentFailed","target":"/subscriptions/c8dde15a-a34e-4149-8afb-d1adae70fa2d/resourceGroups/az-rg-kecka1-01/providers/Microsoft.Resources/deployments/deploy","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-deployment-operations for usage details.","details":[{"code":"ResourceDeploymentFailure","target":"/subscriptions/c8dde15a-a34e-4149-8afb-d1adae70fa2d/resourceGroups/az-rg-kecka1-01/providers/Microsoft.Resources/deployments/WdApi-Development","message":"The resource write operation failed to complete successfully, because it reached terminal provisioning state 'Failed'.","details":[{"code":"DeploymentFailed","target":"/subscriptions/c8dde15a-a34e-4149-8afb-d1adae70fa2d/resourceGroups/az-rg-kecka1-01/providers/Microsoft.Resources/deployments/WdApi-Development","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-deployment-operations for usage details.","details":[{"code":"","message":"{\"error\":{\"code\":\"BadRequest\",\"target\":\"/resources/updateAppRegistration\",\"message\":\"Another object with the same value for property uniqueName already exists. Graph client request id: e34d1e9b-852e-4df5-b212-1ceeb4057f2c. Graph request timestamp: 2024-12-05T17:48:21Z.\"}}"},{"code":"","message":"{\"error\":{\"code\":\"BadRequest\",\"target\":\"/resources/updateWebRedirectUris\",\"message\":\"Another object with the same value for property uniqueName already exists. Graph client request id: be8db975-3cc6-4755-b672-c3165042d129. Graph request timestamp: 2024-12-05T17:48:21Z.\"}}"}]}]}]}}

**Describe the bug**
We are trying to update an existing App Registration.  We were able to successfully deploy a dozen times yesterday, but now we are getting the error shown above.  We even rolled our bicep files back to a prior version that worked, but we're still getting the error.  What changed?

**To Reproduce**
Run the deployment described above.

**Additional context**
(none)

**Comment by dkershaw10** [comment]
@dougclutter thanks for raising this issue.
Please reconfirm the repro steps.  This issue may be due to the following repro steps:

**Steps:**
1. Deploy Bicep file with application.uniqueName = foo
2. Re-deploy as many times as you like (should be successful)
3. **Delete** application (with application.uniqueName = foo)
4. Deploy Bicep file again

**Expected**
Successful creation of the application

**Actual**
Failure above, with the uniqueness constraint error message

**Questions**: 
1. Did step 3 above happen?
2. To double check, if you open [Microsoft Graph Explorer](https://aka.ms/ge), and do `GET https://graph.microsoft.com/v1.0/directory/deletedItems/microsoft.graph.application`, do you see a record with your application with the `uniqueName` you set in the Bicep file?

If the answer is yes to the questions, then the creation of a new application resource is conflicting with a logically deleted application with the same `uniqueName`. (NOTE the `deletedItems` collection is the equivalent of a recycle bin for Entra directory objects.)

The **workaround/remedy** is:
1. Get the `id` of the deleted item
2. Either: 

   - Permanently delete the deleted item - DELETE https://graph.microsoft.com/v1.0/directory/deletedItems/{id}
   - Restore the deleted item - POST https://graph.microsoft.com/v1.0/directory/deletedItems/{id}/restore

**Comment by dougclutter** [comment]
Hi @dkershaw10,
Thanks for the quick reply.

We currently create and configure App Registrations in the Portal; we're just starting to use bicep files.

I think the disconnect happened when I incorrectly assumed that the `Object Id` shown in the Portal was the same as the `uniqueName` in the bicep file.  

We're going to try following the instructions in [Onboard existing Microsoft Graph resources...](https://learn.microsoft.com/en-us/graph/templates/how-to-reference-existing-resources?tabs=CLI) and see where that takes us.  I would *highly* recommend that this article be made more prominent in the docs; it's currently buried in the **How-to Guides** section.

Thanks for pointing us in the right direction!
